[project]
name = "bubbola"
version = "0.1.0"
description = "A Python application with executable distribution"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    # Add your dependencies here
    # "requests>=2.28.0",
    # "click>=8.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
    "pyinstaller>=5.0.0",
]

[project.scripts]
bubbola = "bubbola.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
    "pyinstaller>=5.0.0",
] 