name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS builds
          - os: macos-15
            python-version: '3.11'
            arch: x64
            target: macos-x64
          - os: macos-15
            python-version: '3.11'
            arch: arm64
            target: macos-arm64
          
          # Windows builds
          - os: windows-2022
            python-version: '3.11'
            arch: x64
            target: windows-x64
          
          # Ubuntu builds
          - os: ubuntu-22.04
            python-version: '3.11'
            arch: x64
            target: linux-x64

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[build]"

    - name: Build binary
      run: |
        python scripts/build_binary.py --output-dir dist/${{ matrix.target }}

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: bubbola-${{ matrix.target }}
        path: dist/${{ matrix.target }}/bubbola*
        retention-days: 30

  # Create release when tag is pushed
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/bubbola-macos-x64/bubbola
          artifacts/bubbola-macos-arm64/bubbola
          artifacts/bubbola-windows-x64/bubbola.exe
          artifacts/bubbola-linux-x64/bubbola
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 